#ifndef ARGUS_STATUS_H
#define ARGUS_STATUS_H

typedef enum {
    ARGUS_STATUS_OK = 0,
    ARGUS_STATUS_INVALID_ARGUMENT = -1,
    ARGUS_STATUS_NOT_INITIALIZED = -2,
    ARGUS_STATUS_I2C_WRITE_FAILED = -3,
    ARGUS_STATUS_I2C_READ_FAILED = -4,
    ARGUS_STATUS_OUT_OF_RANGE = -5,
} argus_status_t;

#endif
